# Generated by Django 4.2 on 2024-07-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_contacto_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
